# To make a random range of reward seperate value with a colon (:) (ie. 'money: 10.0:15.0')
# You can change the name of the mob in the reward message by adding 'name: "New mob name"' to any mob.  If no name is given then default name is used.
log: false
global:
  money_decrease: false
  exp_decrease: false
  kill_limit: 5
  kill_reset: 30
  creative_earnings: false
  worlds:
  - world
  - world_nether
  - world_the_end
messages:
  reward: "You have earned [REWARD] for killing this [MOB_TYPE]!"
  limit: "Kill a different type of mob to continue receiving rewards"
mobs:
  BABY_ZOMBIE:
    money: 10.0
    name: "Little Zom"
  BLAZE:
    money: 10.0
  CAVE_SPIDER:
    money: 10.0
  CREEPER:
    money: 10.0
  ENDER_DRAGON:
    money: 200.0
  ENDERMAN:
    money: 10.0
  GHAST:
    money: 20.0
  GIANT:
    money: 20.0
  IRON_GOLEM:
    money: 30.0
  MAGMA_CUBE:
    money: 5.0
  PIG_ZOMBIE:
    money: 12.0
  PLAYER:
    money: 15.0
  SILVERFISH:
    money: 1.0
  SKELETON:
    money: 10.0
  SLIME:
    money: 5.0
  SPIDER:
    money: 7.0
  WITCH:
    money: 50.0
  WITHER:
    money: 200.0
  ZOMBIE:
    money: 5.0
